import type { UserPlace } from "./places-store";

/**
 * Catálogo inicial de La Verde. Estos negocios se siembran en el store local
 * la primera vez que el usuario abre la app, de modo que el panel de admin
 * puede gestionarlos como cualquier otro negocio.
 */
export const SEED_PLACES: UserPlace[] = [
  {
    id: "1",
    name: "Pastelería La Habanera",
    category: "Cafetería",
    lat: 23.1365,
    lng: -82.361,
    address: "Calle San Lázaro #125, Centro Habana",
    barrio: "Centro Habana",
    description:
      "Pastelería artesanal con los mejores pasteles de nata de La Habana. Ambiente familiar, ideal para la mañana.",
    schedule: "8:00 – 20:00",
    payments: ["MLC", "CUP"],
    menu: [],
    offer: null,
    status: "active",
    isBoosted: false,
    boostExpiresAt: "",
    rating: 4.5,
    aiTags: ["Café y dulces", "Abierto temprano"],
    distanceLabel: "800m",
    priceLabel: "$3-8 MLC",
    createdAt: 1,
  },
  {
    id: "2",
    name: "Restaurante El Río",
    category: "Restaurante",
    lat: 23.1467,
    lng: -82.3808,
    address: "Malecón 406, Vedado",
    barrio: "Vedado",
    description:
      "Cocina cubana contemporánea con vista al Malecón. Reservaciones recomendadas para cenar.",
    schedule: "12:00 – 23:00",
    payments: ["MLC", "USD"],
    menu: [],
    offer: null,
    status: "active",
    isBoosted: false,
    boostExpiresAt: "",
    rating: 4.3,
    aiTags: ["Vista al mar", "Cocina criolla"],
    distanceLabel: "1.1km",
    priceLabel: "$12-25 MLC",
    createdAt: 2,
  },
  {
    id: "3",
    name: "La Guarida",
    category: "Restaurante",
    lat: 23.1417,
    lng: -82.37,
    address: "Calle Concordia #418, Centro Habana",
    barrio: "Centro Habana",
    description:
      "La Guarida es un restaurante cubano contemporáneo en Centro Habana. Ocupa un edificio art déco de los años 40 con su fachada original de columnas y balcones de hierro forjado. El interior mezcla la arquitectura colonial con diseño moderno: madera oscura, iluminación tenue y arte cubano en las paredes. Lo fundaron en 2018 un grupo de amigos chefs que querían rescatar las recetas de sus abuelas con un toque contemporáneo. La cocina es 100% criolla: ropa vieja, lechón asado, picadillo habanero, tostones y yuca con mojo. Los fines de semana hay música en vivo, son cubano, jazz o trova según el día. Tienen terraza interior con plantas tropicales y una barra de cocktails con rones cubanos premium. Aceptan MLC, CUP y efectivo en USD. Reservaciones recomendadas los viernes y sábados.",
    schedule: "12PM – 12AM",
    payments: ["MLC", "CUP", "USD"],
    menu: [
      {
        name: "Ropa Vieja Tradicional",
        description: "Carne desmechada con sofrito cubano, arroz blanco y plátanos maduros",
        price: "450",
        currency: "CUP",
      },
      {
        name: "Lechón Asado",
        description: "Cerdo asado lentamente con mojo criollo, yuca y ensalada de aguacate",
        price: "12",
        currency: "MLC",
      },
      {
        name: "Cóctel de la Casa",
        description: "Ron añejo, jugo de maracuyá, hierbabuena y un toque de miel de abeja",
        price: "5",
        currency: "MLC",
      },
      {
        name: "Tostones con Mojo",
        description: "Plátano verde frito con ajo, naranja agria y cebolla morada",
        price: "200",
        currency: "CUP",
      },
    ],
    offer: {
      text: "2x1 en cócteles artesanales de martes a jueves, 6PM – 9PM",
      expiry: "Válido hasta el 15 de agosto · Presentar al pedir",
    },
    status: "active",
    isBoosted: true,
    boostExpiresAt: "",
    rating: 4.7,
    slides: [
      { gradient: "linear-gradient(160deg, oklch(45% 0.08 145), oklch(35% 0.06 145))", label: "Fachada colonial" },
      { gradient: "linear-gradient(160deg, oklch(50% 0.06 85), oklch(40% 0.05 85))", label: "Interior art déco" },
      { gradient: "linear-gradient(160deg, oklch(55% 0.10 75), oklch(42% 0.08 75))", label: "Plato signature" },
      { gradient: "linear-gradient(160deg, oklch(40% 0.04 250), oklch(30% 0.03 250))", label: "Terraza nocturna" },
    ],
    aiReasoning:
      "La Guarida está en Centro Habana, tiene cocina tradicional cubana y un ambiente relajado. Aceptan MLC y tarjeta. Los fines de semana tienen música en vivo.",
    aiTags: ["Cerca de ti", "Comida criolla", "Acepta MLC"],
    distanceLabel: "1.2 km",
    priceLabel: "$15-35 MLC",
    createdAt: 3,
  },
  {
    id: "4",
    name: "Mercado de San José",
    category: "Mercado",
    lat: 23.133,
    lng: -82.352,
    address: "Avenida del Puerto, Habana Vieja",
    barrio: "Habana Vieja",
    description:
      "Mercado artesanal con frutas tropicales, artesanías y souvenirs. Los mejores precios en fruta fresca.",
    schedule: "9:00 – 18:00",
    payments: ["CUP"],
    menu: [],
    offer: null,
    status: "active",
    isBoosted: false,
    boostExpiresAt: "",
    rating: 4.2,
    aiTags: ["Frutas frescas", "Artesanías"],
    distanceLabel: "2.1km",
    priceLabel: "CUP",
    createdAt: 4,
  },
  {
    id: "5",
    name: "Fábrica de Arte Cubano",
    category: "Vida nocturna",
    lat: 23.144,
    lng: -82.39,
    address: "Calle 26 esq. 11, Vedado",
    barrio: "Vedado",
    description:
      "El espacio cultural más vibrante de La Habana. Arte, música en vivo, cine y gastronomía.",
    schedule: "18:00 – 02:00",
    payments: ["MLC", "USD"],
    menu: [],
    offer: null,
    status: "active",
    isBoosted: false,
    boostExpiresAt: "",
    rating: 4.7,
    aiTags: ["Música en vivo", "Arte y cultura"],
    distanceLabel: "650m",
    priceLabel: "$8-20 MLC",
    createdAt: 5,
  },
  {
    id: "6",
    name: "Café El Ignoto",
    category: "Cafetería",
    lat: 23.142,
    lng: -82.385,
    address: "Calle 23 #310, Vedado",
    barrio: "Vedado",
    description:
      "Café de especialidad en Vedado. Acepta MLC, ideal para trabajar o leer tranquilo.",
    schedule: "9:00 – 22:00",
    payments: ["MLC"],
    menu: [],
    offer: null,
    status: "active",
    isBoosted: false,
    boostExpiresAt: "",
    rating: 4.8,
    aiTags: ["Café de especialidad", "Tranquilo"],
    distanceLabel: "350m",
    priceLabel: "$5-12 MLC",
    createdAt: 6,
  },
];
